### ISSUE TITLE
求解一个bug

### ISSUE THREAD

**Issue by csy1997** [LeeJiangWei/pcr-calculator#7]
开发者你好，本人新手今天按照教程安装并操作了下，出现了些问题，想请教一下。
具体是：在安装完成后开启插件，进入图书馆装备库选了两个角色储存，打开插件选项卡点击前两个按钮，没有明显反应，点计算按钮时控制台会报以下错误，
![image](https://user-images.githubusercontent.com/47239672/103154520-c0e6fd80-47d2-11eb-85ea-e17bc2c6aabb.png)

Error handling response: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at n.loadJson (chrome-extension://daelbliafajbhfjcejplngniblcdbgkb/contents/solver.js:427:30)
    at i.Solve (chrome-extension://daelbliafajbhfjcejplngniblcdbgkb/contents/solver.js:1942:55)
    at calculate (chrome-extension://daelbliafajbhfjcejplngniblcdbgkb/contents/calculate.js:29:25)
    at chrome-extension://daelbliafajbhfjcejplngniblcdbgkb/contents/calculate.js:3:3

也没有结果显示，除此之外插件扩展程序里新增了如下错误，
![L@$@D})1KYNWA`4BF_DE( 9](https://user-images.githubusercontent.com/47239672/103154586-4a96cb00-47d3-11eb-8ba4-dc8b3a5cc500.png)
插件选项栏里的参数都是默认的没有修改。
如果有时间的话麻烦大佬帮忙看下，谢谢~~

**Comment by cznull** [comment]
刚提交了pr，可以根据网页变化修了点地方，暂时能解决问题

**Comment by csy1997** [comment]
> 刚提交了pr，可以根据网页变化修了点地方，暂时能解决问题

你好试了下你提交的内容，好像还是有一样的问题，不知具体原因是什么

**Comment by LeeJiangWei** [comment]
抱歉前一阵子比较忙，现在应该修好了可以了

> 刚提交了pr，可以根据网页变化修了点地方，暂时能解决问题

今天自己修好了才看到PR，感谢贡献
